name: Test build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - architecture: amd64
            os: ubuntu-24.04
          - architecture: arm64
            os: ubuntu-24.04-arm 
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install snapcraft cli
        run: |
          sudo snap install snapcraft --classic

      - name: Build snap
        run: |
          sudo snapcraft pack --destructive-mode
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
          USE_SYSTEM_FPM: true

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-${{ matrix.architecture }}-snap
          path: "*.snap"
          
  i386-build:
    runs-on: ubuntu-22.04 # for the best compat we have
    steps:
      - uses: actions/checkout@v6

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v4
      #   with:
      #     platforms: i386 # hope platforms supports i386 the docs don't mention it
      - name: Patch manifest for core18
        run: |
          # swap core
          sed -i 's/base: core24/base: core18/g' snapcraft.yaml
          
          # swap platforms block for the architectures one
          # cuz that's what older snapcraft uses
          sed -i '/platforms:/,/summary:/ { /summary:/!d }' snapcraft.yaml
          sed -i '/summary:/i architectures:\n  - build-on: [amd64, i386]\n    run-on: [i386]\n' snapcraft.yaml

          # use configflags as replacement for cmake-parameters
          # i thought i misread the docs but turns out i didnt
          sed -i 's/cmake-parameters:/configflags:/g' snapcraft.yaml
          sed -i '/cmake-generator:/d' snapcraft.yaml

          # remove extension line
          # cuz snapcraft says that gnome doesn't exist
          # in core18 even though that is false
          sed -i '/extensions:/d' snapcraft.yaml

          # the libgtk packages basically
          # do the same stuff that gnome extension did
          # old code
          #####sed -i '/build-packages:/a \      - libgtk-3-dev:i386\n      - libglib2.0-dev:i386' snapcraft.yaml
          # end of old code


          # craftctl doesn't exist on core18...
          sed -i '/override-pull:/,/craftctl default/ s/craftctl default/snapcraftctl pull/' snapcraft.yaml
          sed -i '/override-build:/,/craftctl default/ s/craftctl default/snapcraftctl build/' snapcraft.yaml

          # below is a last resort
          # not a good idea
          ####sed -i '/discord-rpc:/,/kart-app:/ s/craftctl default/snapcraftctl build/' snapcraft.yaml
                    
          # swap ENV beginning parts (may not work properly, but we will see)
          sed -i 's/\$CRAFT_/\$SNAPCRAFT_/g' snapcraft.yaml
          
          # patch find command for binary
          # to SNAPCRAFT_PART_BUILD from cwd (.)
          sed -i 's/kart=$(find . -name "srb2kart"/kart=$(find ..\/..\/..\/.. -name "srb2kart"/g' snapcraft.yaml   
          sed -i 's/-name "srb2kart"/-iname "*srb2kart*"/g' snapcraft.yaml
          sed -i 's/rpc=$(find . -name "libdiscord-rpc.so"/rpc=$(find ..\/..\/..\/.. -name "libdiscord-rpc.so"/g' snapcraft.yaml

          
          # trust the apt sources
          # not just for the soundfont lib
          # in case this happens with other libs
          # using an apt config
          # no idea why this only happens here
          # guess it is core18 or snapcraft v7??
          echo "Acquire::AllowInsecureRepositories \"true\";
          Acquire::AllowUnauthenticated \"true\";
          APT::Get::AllowUnauthenticated \"true\";
          Acquire::https::Verify-Peer \"false\";" | sudo tee /etc/apt/apt.conf.d/99force-trust
          
          # enable multiverse cuz of the soundfont lib timgm6mb-soundfont
          sudo apt-add-repository multiverse -y
          
          # apply
          sudo apt-get update

          echo "patched yaml:"
          cat snapcraft.yaml
      # - name: Setup lxd
      #   uses: canonical/setup-lxd@v1
      
      # - name: Build snap 
      # (this is old one that used stupid lxd workarounds that didn't even work)
      #   run: |
      #     sudo snap install snapcraft --classic --channel=7.x/stable

      #     # hopefully it doesn't ask for password
      #     # if we chmod this properly
      #     # if it does then...
      #     sudo chmod 666 /var/snap/lxd/common/lxd/unix.socket

      #     # okay just force add the socket
      #     # if this doesn't work.......
      #     lxc remote add local unix:///var/snap/lxd/common/lxd/unix.socket --accept-certificate || true
      #     lxc remote switch local

      #     snapcraft --use-lxd

      - name: Build snap
        run: |
          # add i386 packages
          sudo dpkg --add-architecture i386
          sudo apt-get update
          
          # snapcraft v7 is the last to support core18
          # and core18 is the last core to support i386
          # so anyone debugging don't upgrade core or snapcraft
          # snapcraft v8 with core24 wont work for i386
          sudo snap install snapcraft --classic --channel=7.x/stable

          # setarch just spoofs what arch values it passes
          # directly to the snapcraft proc
          # so it doesn't detect the host arch properly
          # and do an amd64 build
          # dunno if this will work too well with --destructive-mode tho
          setarch i386 snapcraft --destructive-mode

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-i386-snap
          path: "*.snap"

  riscv64-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup qemu
        run: |
          sudo apt-get update
          # for qemu and binary changes in kernel level
          # so we can even do riscv64
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --enable qemu-riscv64 # now enable riscv64 super fast
                                                    # so qemu doesn't take its time
                                                    # using the binfmt cli from binfmt-support'
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes # register qemu
          # so it takes effect finally now

      - name: Patch manifest
        run: |
          cat <<EOF > build-patch.yaml
          platforms:
            riscv64:
              build-on: [amd64]
              build-for: [riscv64]
          EOF
          # use a heredoc so snapcraft knows we're using amd64
          # but build for riscv64
          # using the registered qemu
          # since it whines about not being able to build a snap
          # with amd64 AND riscv64 support for some reason
          
          # now use sed to patch the platforms key
          # with our cool patch
          sed -i '/platforms:/,/^[a-z]/ { /platforms:/! { /^[a-z]/!d } }' snapcraft.yaml
          sed -i '/platforms:/d' snapcraft.yaml
          
          # maybe a patchfile would be better tho
          cat build-patch.yaml >> snapcraft.yaml
          
          # double check the yaml after the heredoc
          cat snapcraft.yaml

      - name: Setup lxd
        uses: canonical/setup-lxd@v1
      
      - name: Build snap
        run: |
          sudo snap install snapcraft --classic --channel=latest/stable
          sudo snapcraft --use-lxd --build-for=riscv64

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-riscv64-snap
          path: "*.snap"

  armhf-build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Setup qemu
        uses: docker/setup-qemu-action@v4

      - name: Patch manifest
        run: |
          cat <<EOF > build-patch.yaml
          platforms:
            armhf:
              build-on: [arm64]
              build-for: [armhf]
          EOF
          # use a heredoc so snapcraft knows we're using arm64
          # but build for armhf
          # using the registered qemu
          # since it whined about not being able to build a snap
          # with amd64 AND riscv64 support for some reason
          # in the riscv64 build workflow
          
          # now use sed to patch the platforms key
          # with our cool patch
          sed -i '/platforms:/,/^[a-z]/ { /platforms:/! { /^[a-z]/!d } }' snapcraft.yaml
          sed -i '/platforms:/d' snapcraft.yaml
          
          # maybe a patchfile would be better tho
          cat build-patch.yaml >> snapcraft.yaml
          
          # double check the yaml after the heredoc
          cat snapcraft.yaml

          # long sed warning
          # patch the snapcraft.yaml
          # again so the linter does not whine about
          # missing libs because it did that in one build
          # and i would rather not break armhf potentially
          sed -i '/dependencies:/,/prime:/ s|prime:|prime:\n      - usr/local/srb2kart/*.so*\n      - usr/games/SRB2Kart/*.so*|' snapcraft.yaml

      - name: Setup lxd
        uses: canonical/setup-lxd@v1
      
      - name: Build snap
        run: |
          sudo snap install snapcraft --classic --channel=latest/stable
          sudo snapcraft --use-lxd --build-for=armhf

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-armhf-snap
          path: "*.snap"

  # publish-snap:
  #   needs: [test-build,riscv64-build,armhf-build]
  #   # very lengthy if warning
  #   if: always() && needs.test-build.result == 'success' && needs.riscv64-build.result == 'success' && needs.armhf-build.result == 'success'
  #   uses: ./.github/workflows/publish-snap.yml
  #   with:
  #     channel: 'edge'
  #   secrets: inherit
