name: Test build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    strategy:
      matrix:
        include:
          - architecture: amd64
            os: ubuntu-24.04
          - architecture: arm64
            os: ubuntu-24.04-arm 
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install snapcraft cli
        run: |
          sudo snap install snapcraft --classic

      - name: Build snap
        run: |
          sudo snapcraft pack --destructive-mode
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
          USE_SYSTEM_FPM: true

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-${{ matrix.architecture }}-snap
          path: "*.snap"
          
  # i386-build:
  #   runs-on: ubuntu-22.04 # for the best compat we have
  #   steps:
  #     - uses: actions/checkout@v6

  #     - name: Install qemu for emulation
  #       run: |
  #         sudo apt-get update
  #         # for qemu and binary changes in kernel level
  #         # so we can even do riscv64
  #         sudo apt-get install -y qemu-user-static binfmt-support
  #         sudo update-binfmts --enable qemu-i386 # now enable i386
  #         # cuz lxd wont work without it
  #     - name: Patch manifest for core18
  #       run: |
  #         # swap core
  #         sed -i 's/base: core24/base: core18/g' snapcraft.yaml
  #         # swap gnome extension to older variant
  #         # cuz just gnome doesn't exist for core18 i think
  #         sed -i 's/extensions: \[ gnome \]/extensions: \[ gnome-3-34 \]/g' snapcraft.yaml
          
  #         # swap platforms block for the architectures one
  #         # cuz that's what older snapcraft uses
  #         sed -i '/platforms:/,/summary:/ { /summary:/!d }' snapcraft.yaml
  #         sed -i '/summary:/i architectures:\n  - build-on: [amd64, i386]\n    run-on: [i386]\n' snapcraft.yaml
          
  #         # swap cmake-parameters to configflags as used with older snapcraft
  #         sed -i 's/cmake-parameters:/configflags:/g' snapcraft.yaml

  #     - name: Setup lxd
  #       uses: canonical/setup-lxd@v1
      
  #     - name: Build snap
  #       run: |
  #         sudo snap install snapcraft --classic --channel=7.x/stable
  #         ##sudo lxc remote add images https://images.linuxcontainers.org --protocol shiftfs || true
  #         sudo snapcraft --use-lxd

  #     - name: Upload snap
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: srb2kart-i386-snap
  #         path: "*.snap"

  riscv64-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install qemu for emulation
        run: |
          sudo apt-get update
          # for qemu and binary changes in kernel level
          # so we can even do riscv64
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --enable qemu-riscv64 # now enable riscv64 super fast
                                                    # so qemu doesn't take its time
                                                    # using the binfmt cli from binfmt-support'
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes # register qemu
          # so it takes effect finally now

      - name: Patch manifest
        run: |
          cat <<EOF > build-patch.yaml
          platforms:
            riscv64:
              build-on: [amd64]
              build-for: [riscv64]
          EOF
          # use a heredoc so snapcraft knows we're using amd64
          # but build for riscv64
          # using the registered qemu
          # since it whines about not being able to build a snap
          # with amd64 AND riscv64 support for some reason
          
          # now use sed to patch the platforms key
          # with our cool patch
          sed -i '/platforms:/,/^[a-z]/ { /platforms:/! { /^[a-z]/!d } }' snapcraft.yaml
          sed -i '/platforms:/d' snapcraft.yaml
          
          # maybe a patchfile would be better tho
          cat build-patch.yaml >> snapcraft.yaml
          
          # double check the yaml after the heredoc
          cat snapcraft.yaml

      - name: Setup lxd
        uses: canonical/setup-lxd@v1
      
      - name: Build snap
        run: |
          sudo snap install snapcraft --classic --channel=latest/stable
          sudo snapcraft --use-lxd --build-for=riscv64

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-riscv64-snap
          path: "*.snap"

  armhf-build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Install qemu for emulation
        run: |
          sudo apt-get update
          # for qemu and binary changes in kernel level
          # so even if the chip doesn't have 32 bit cores
          # (which could be a reason why armhf builds might fail)
          sudo apt-get install -y qemu-user-static binfmt-support
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes # register qemu
          # so it takes effect finally now

      - name: Patch manifest
        run: |
          cat <<EOF > build-patch.yaml
          platforms:
            armhf:
              build-on: [arm64]
              build-for: [armhf]
          EOF
          # use a heredoc so snapcraft knows we're using arm64
          # but build for armhf
          # using the registered qemu
          # since it whined about not being able to build a snap
          # with amd64 AND riscv64 support for some reason
          # in the riscv64 build workflow
          
          # now use sed to patch the platforms key
          # with our cool patch
          sed -i '/platforms:/,/^[a-z]/ { /platforms:/! { /^[a-z]/!d } }' snapcraft.yaml
          sed -i '/platforms:/d' snapcraft.yaml
          
          # maybe a patchfile would be better tho
          cat build-patch.yaml >> snapcraft.yaml
          
          # double check the yaml after the heredoc
          cat snapcraft.yaml

      - name: Setup lxd
        uses: canonical/setup-lxd@v1
      
      - name: Build snap
        run: |
          sudo snap install snapcraft --classic --channel=latest/stable
          sudo snapcraft --use-lxd --build-for=armhf

      - name: Upload snap
        uses: actions/upload-artifact@v6
        with:
          name: srb2kart-riscv64-snap
          path: "*.snap"

  publish-snap:
    needs: [test-build,riscv64-build,armhf-build]
    # very lengthy if warning
    if: always() && needs.test-build.result == 'success' && needs.riscv64-build.result == 'success' && needs.armhf-build.result == 'success'
    uses: ./.github/workflows/publish-snap.yml
    with:
      channel: 'edge'
    secrets: inherit
